FROM node:lts-alpine

WORKDIR /usr/app

RUN chown -R node:node /usr/app

RUN apk add --no-cache build-base gcc autoconf automake libtool zlib-dev libpng-dev nasm

USER node

COPY --chown=node:node ./package.json .

RUN yarn

COPY --chown=node:node . .

CMD ["yarn", "dev"]
