version: "3"

networks:
  frontend:
    # external: true
    driver: ${NETWORKS_DRIVER}
  backend:
    # external: false
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  mariadb:
    driver: ${VOLUMES_DRIVER}
  postgres:
    driver: ${VOLUMES_DRIVER}
  mongo:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}
  webhook:
    driver: ${VOLUMES_DRIVER}

services:
  ### Application ################################################
  app:
    depends_on:
      - traefik
      # - strapi
    restart: always
    build:
      context: ../app/
    volumes:
      - ${APP_CODE_PATH_CONTAINER}/app/node_modules
      - ${APP_CODE_PATH_HOST}/app:${APP_CODE_PATH_CONTAINER}/app
    environment:
      HOST: 0.0.0.0
    networks:
      - frontend
    expose:
      - "3000"
    labels:
      - "traefik.backend=app"
      - "traefik.frontend.rule=Host:${APP_WEB_URL}"
      - "traefik.port=3000"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_frontend"

  ## PRISMA ################################################
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    environment:
      PRISMA_CONFIG: |
        ## The Management API secret is used by the Prisma CLI to generate authentication tokens and authenticate its requests against the Prisma server.
        # managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4466
        databases:
          ## MongoDB ##
          default:
            connector: ${API_DATABASE_CLIENT}
            uri: mongodb://${API_DATABASE_USERNAME}:${API_DATABASE_USERNAME}@${API_DATABASE_HOST}
            migrations: ${PRISMA_MIGRATIONS}
            ssl: ${API_DATABASE_SSL}
            ## The maximum number of database connections (must be at least 2).
            # connectionLimit: ${PRISMA_CONNECTION_LIMIT}
          ## SQL ##
          # default:
          # connector: ${API_DATABASE_CLIENT}
          # host: ${API_DATABASE_HOST}
          # port: ${API_DATABASE_PORT}
          # user: ${API_DATABASE_USERNAME}
          # password: ${API_DATABASE_PASSWORD}
          # migrations: ${PRISMA_MIGRATIONS}
          # ssl: ${API_DATABASE_SSL}
          # connectionLimit: ${PRISMA_CONNECTION_LIMIT}
    networks:
      - frontend
      - backend
    labels:
      - "traefik.backend=prisma"
      - "traefik.frontend.rule=Host:${PRISMA_WEB_URL}"
      - "traefik.port=4466"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_frontend"

  ## STRAPI ################################################
  strapi:
    depends_on:
      - ${API_DATABASE_CLIENT}
    build:
      context: ./strapi
    restart: unless-stopped
    expose:
      - "1337"
    networks:
      - frontend
      - backend
    environment:
      - DATABASE_HOST=${API_DATABASE_HOST}
      - DATABASE_PORT=${API_DATABASE_PORT}
      - DATABASE_SRV=${API_DATABASE_SRV}
      - DATABASE_NAME=${API_DATABASE_NAME}
      - DATABASE_USERNAME=${API_DATABASE_USERNAME}
      - DATABASE_PASSWORD=${API_DATABASE_PASSWORD}
      - DATABASE_SSL=${API_DATABASE_SSL}
      - DATABASE_AUTHENTICATION_DATABASE=${API_DATABASE_AUTHENTICATION_DATABASE}
    labels:
      - "traefik.backend=strapi"
      - "traefik.frontend.rule=Host:${API_HOST_URL}"
      - "traefik.port=1337"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_frontend"
    volumes:
      - ${APP_CODE_PATH_CONTAINER}/api/node_modules
      - ./strapi:${APP_CODE_PATH_CONTAINER}/api

  ### MySQL ################################################
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${API_DATABASE_NAME}
      - MYSQL_USER=${API_DATABASE_USERNAME}
      - MYSQL_PASSWORD=${API_DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    networks:
      - backend
    labels:
      - traefik.enable=false

  ### MariaDB ##############################################
  mariadb:
    build:
      context: ./mariadb
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - MARIADB_VERSION=${MARIADB_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
      - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
      - MYSQL_DATABASE=${API_DATABASE_NAME}
      - MYSQL_USER=${API_DATABASE_USERNAME}
      - MYSQL_PASSWORD=${API_DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    networks:
      - backend
    labels:
      - traefik.enable=false

    ### PostgreSQL ###########################################
    postgres:
      build: ./postgres
      volumes:
        - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
        - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
      ports:
        - "${POSTGRES_PORT}:5432"
      environment:
        - POSTGRES_DB=${API_DATABASE_NAME}
        - POSTGRES_USER=${API_DATABASE_USERNAME}
        - POSTGRES_PASSWORD=${API_DATABASE_PASSWORD}
      networks:
        - backend
      labels:
        - traefik.enable=false

  ### MongoDB ##############################################
  mongo:
    build:
      context: ./mongo
      args:
        - MONGO_VERSION=${MONGO_VERSION}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${API_DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${API_DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${API_DATABASE_NAME}
    volumes:
      - ${DATA_PATH_HOST}/mongo:/data/db
    networks:
      - backend
    labels:
      - traefik.enable=false

  ### Mongo Express ##############################################
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    networks:
      - frontend
      - backend
    labels:
      - "traefik.backend=mongo-express"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_frontend"
      - "traefik.frontend.rule=Host:${ME_URL}"
      - "traefik.port=8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${API_DATABASE_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${API_DATABASE_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: ${ME_CONFIG_MONGODB_ENABLE_ADMIN}
      ME_CONFIG_MONGODB_AUTH_DATABASE: ${API_DATABASE_AUTHENTICATION_DATABASE}
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${API_DATABASE_USERNAME}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${API_DATABASE_PASSWORD}

  ### Jenkins ###################################################
  jenkins:
    build: ./jenkins
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "${JENKINS_HOST_SLAVE_AGENT_PORT}:50000"
      # - "${JENKINS_HOST_HTTP_PORT}:8080"
    privileged: true
    volumes:
      - ${JENKINS_HOME}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend
      - backend
    labels:
      - "traefik.backend=jenkins"
      - "traefik.frontend.rule=Host:${JENKINS_URL}"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_frontend"
      - "traefik.port=8080"

  ### Webhook ###################################################
  webhook:
    build: ./webhook
    volumes:
      - ${WEBHOOK_HOOKS_DIR}:/etc/webhook
      - ${WEBHOOK_SCRIPTS_DIR}:/opt/scripts
      - ${APP_CODE_PATH_HOST}:/opt/deploy
    networks:
      - frontend
    labels:
      - "traefik.backend=webhook"
      - "traefik.frontend.rule=Host:${WEBHOOK_URL}"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_frontend"
      - "traefik.port=9000"

  ### Adminer ################################################
  adminer:
    image: adminer:4.7.3-standalone
    restart: unless-stopped
    environment:
      - ADMINER_DESIGN=${ADMINER_DESIGN}
    labels:
      - "traefik.backend=adminer"
      - "traefik.frontend.rule=Host:${ADMINER_URL}"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_frontend"
      - "traefik.port=8080"
    networks:
      - frontend
      - backend
    depends_on:
      - ${ADMINER_HOST}

  ### TRAEFIK #########################################
  traefik:
    build:
      context: ./traefik
    restart: always
    command: --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${TRAEFIK_HOST_HTTP_PORT}:80"
      - "${TRAEFIK_HOST_HTTPS_PORT}:443"
    networks:
      - frontend
    labels:
      - "traefik.backend=traefik"
      - "traefik.frontend.rule=Host:${TRAEFIK_WEB_URL}"
      - "traefik.port=8080"

  ### Redis ################################################
  redis:
    build: ./redis
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend
    labels:
      - traefik.enable=false

  ### Redis Cluster ##########################################
  redis-cluster:
    build: ./redis-cluster
    ports:
      - "${REDIS_CLUSTER_PORT_RANGE}:7000-7005"
    networks:
      - backend
    labels:
      - traefik.enable=false

  ### REDISWEBUI ################################################
  redis-webui:
    build:
      context: ./redis-webui
    environment:
      - ADMIN_USER=${REDIS_WEBUI_USERNAME}
      - ADMIN_PASS=${REDIS_WEBUI_PASSWORD}
      - REDIS_1_HOST=${REDIS_WEBUI_CONNECT_HOST}
      - REDIS_1_PORT=${REDIS_WEBUI_CONNECT_PORT}
    networks:
      - frontend
      - backend
    depends_on:
      - redis
    labels:
      - "traefik.backend=redis"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_frontend"
      - "traefik.frontend.rule=Host:${REDIS_WEBUI_URL}"
      - "traefik.port=80"
