# @format

version: '3.9'

networks:
  # docker network create --subnet 192.168.90.0/24 --gateway 192.168.90.1 backdocker
  dockernet:
    external: true
  # docker network create --subnet 192.168.90.0/24 --gateway 192.168.90.1 backdocker
  backdocker:
    external: true

services:
  ## Application ################################################
  frontend:
    restart: always
    build:
      context: ../frontend/
    volumes:
      - ${APP_CODE_PATH_CONTAINER}/app/node_modules
      - ${APP_CODE_PATH_HOST}/app:${APP_CODE_PATH_CONTAINER}/app
    env_file: ../frontend/.env
    depends_on:
      - traefik
    networks:
      - dockernet
    labels:
      - 'traefik.enable=true'

  ###############################################
  # Adonis Microservices ################################################

  authors:
    restart: always
    build:
      context: ../${MS_DIR}/${MS_ONE}
      dockerfile: Dockerfile.v5.dev
    volumes:
      - ${APP_CODE_PATH_CONTAINER}/api/node_modules
      - ${APP_CODE_PATH_HOST}/${MS_DIR}/${MS_ONE}:${APP_CODE_PATH_CONTAINER}/api
    env_file: ../${MS_DIR}/${MS_ONE}/.env
    depends_on:
      - ${API_DATABASE_CLIENT}
    networks:
      - dockernet
      - backdocker
    labels:
      - 'traefik.enable=true'
