version: "3"

networks:
  frontend:
    # external: true
    driver: ${NETWORKS_DRIVER}
  backend:
    # external: false
    driver: ${NETWORKS_DRIVER}

volumes:
  mysql:
    driver: ${VOLUMES_DRIVER}
  mariadb:
    driver: ${VOLUMES_DRIVER}
  postgres:
    driver: ${VOLUMES_DRIVER}
  mongo:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}
  webhook:
    driver: ${VOLUMES_DRIVER}

services:
  ### Application ################################################
  frontend:
    depends_on:
      - traefik
    restart: always
    build:
      context: ../app/
    volumes:
      - ${APP_CODE_PATH_CONTAINER}/app/node_modules
      - ${APP_CODE_PATH_HOST}/app:${APP_CODE_PATH_CONTAINER}/app
    environment:
      HOST: 0.0.0.0
    networks:
      - frontend
    labels:
      - "traefik.backend=${TB_APP}"
      - "traefik.frontend.rule=Host:${APP_HOST_URL}"
      - "traefik.port=${APP_CONTAINER_PORT}"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_frontend"

  ## Adonis Microservices ################################################

  authors:
    depends_on:
      - ${API_DATABASE_CLIENT}
    restart: always
    build:
      context: ../microservices/${MS_ONE}
      dockerfile: Dockerfile.v5.dev
    volumes:
      - ${APP_CODE_PATH_CONTAINER}/api/node_modules
      - ${APP_CODE_PATH_HOST}/${MS_ONE}:${APP_CODE_PATH_CONTAINER}/api
    environment:
      HOST: 0.0.0.0
    networks:
      - frontend
      - backend
    labels:
      - "traefik.backend=${MS_ONE}"
      - "traefik.frontend.rule=Host:${MS_ONE_HOST_URL}"
      - "traefik.port=${MS_ONE_PORT}"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_frontend"

  ## API ################################################

  graphql:
    build:
      context: graphql
      args:
        NODE_ENV: ${GRAPHQL_API_ENV}
    restart: always
    environment:
      NODE_ENV: ${GRAPHQL_API_ENV}
      PRISMA_ENDPOINT: ${PRISMA_ENDPOINT}
      PRISMA_SECRET: ${PRISMA_SECRET}
      APP_SECRET: ${GRAPHQL_API_APP_SECRET}
      BCRYPT_SALT_ROUNDS: ${GRAPHQL_API_BCRYPT_SALT_ROUNDS}
      FRONTEND_URL: ${GRAPHQL_PRISMA_FRONTEND_URL}
      BACKEND_URL: ${GRAPHQL_PRISMA_BACKEND_URL}
      PLAYGROUND_URL: ${GRAPHQL_PRISMA_PLAYGROUND_URL}
    volumes:
      - ${APP_CODE_PATH_CONTAINER}/api/node_modules
      - ./graphql/src:${APP_CODE_PATH_CONTAINER}/api/src
    networks:
      - frontend
    depends_on:
      - prisma
    labels:
      - "traefik.backend=${TB_GRAPHQL}"
      - "traefik.frontend.rule=Host:${GRAPHQL_API_HOST_URL}"
      - "traefik.port=${GRAPHQL_CONTAINER_PORT}"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_frontend"

  ## PRISMA ################################################
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - "${PRISMA_CONTAINER_PORT}:${PRISMA_CONTAINER_PORT}"
    environment:
      LOG_LEVEL: TRACE
      PRISMA_CONFIG: |
        LOG_LEVEL: TRACE
        ## The Management API secret is used by the Prisma CLI to generate authentication tokens and authenticate its requests against the Prisma server.
        # managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        port: 4466
        databases:
          ## MongoDB ##
          default:
            database: ${API_DATABASE_NAME}
            connector: ${API_DATABASE_CLIENT}
            uri: mongodb://${API_DATABASE_USERNAME}:${API_DATABASE_PASSWORD}@${API_DATABASE_HOST}/${API_DATABASE_AUTHENTICATION_DATABASE}
            migrations: ${PRISMA_MIGRATIONS}
            ssl: ${API_DATABASE_SSL}
            ## The maximum number of database connections (must be at least 2).
            # connectionLimit: ${PRISMA_CONNECTION_LIMIT}
          ## SQL ##
          # default:
          # database: ${API_DATABASE_NAME}
          # connector: ${API_DATABASE_CLIENT}
          # host: ${API_DATABASE_HOST}
          # port: ${API_DATABASE_PORT}
          # user: ${API_DATABASE_USERNAME}
          # password: ${API_DATABASE_PASSWORD}
          # migrations: ${PRISMA_MIGRATIONS}
          # ssl: ${API_DATABASE_SSL}
          # connectionLimit: ${PRISMA_CONNECTION_LIMIT}
    networks:
      - frontend
      - backend
    labels:
      - "traefik.backend=${TB_PRISMA}"
      - "traefik.frontend.rule=Host:${PRISMA_HOST_URL}"
      - "traefik.port=${PRISMA_CONTAINER_PORT}"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_frontend"

  ## STRAPI ################################################
  strapi:
    depends_on:
      - ${API_DATABASE_CLIENT}
    build:
      context: ./strapi
    restart: unless-stopped
    networks:
      - frontend
      - backend
    environment:
      - DATABASE_HOST=${API_DATABASE_HOST}
      - DATABASE_PORT=${API_DATABASE_PORT}
      - DATABASE_SRV=${API_DATABASE_SRV}
      - DATABASE_NAME=${API_DATABASE_NAME}
      - DATABASE_USERNAME=${API_DATABASE_USERNAME}
      - DATABASE_PASSWORD=${API_DATABASE_PASSWORD}
      - DATABASE_SSL=${API_DATABASE_SSL}
      - DATABASE_AUTHENTICATION_DATABASE=${API_DATABASE_AUTHENTICATION_DATABASE}
    labels:
      - "traefik.backend=${TB_STRAPI}"
      - "traefik.frontend.rule=Host:${STRAPI_HOST_URL}"
      - "traefik.port=${STRAPI_CONTAINER_PORT}"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_frontend"
    volumes:
      - ${APP_CODE_PATH_CONTAINER}/api/node_modules
      - ./strapi:${APP_CODE_PATH_CONTAINER}/api

  ### MySQL ################################################
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=${API_DATABASE_NAME}
      - MYSQL_USER=${API_DATABASE_USERNAME}
      - MYSQL_PASSWORD=${API_DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    networks:
      - backend
    labels:
      - traefik.enable=false

  ### MariaDB ##############################################
  mariadb:
    build:
      context: ./mariadb
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - MARIADB_VERSION=${MARIADB_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
      - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - TZ=${WORKSPACE_TIMEZONE}
      - MYSQL_DATABASE=${API_DATABASE_NAME}
      - MYSQL_USER=${API_DATABASE_USERNAME}
      - MYSQL_PASSWORD=${API_DATABASE_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    networks:
      - backend
    labels:
      - traefik.enable=false

  ### PostgreSQL ###########################################
  postgres:
    build: ./postgres
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
      - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${API_DATABASE_NAME}
      - POSTGRES_USER=${API_DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${API_DATABASE_PASSWORD}
    networks:
      - backend
    labels:
      - traefik.enable=false

  ### MongoDB ##############################################
  mongo:
    build:
      context: ./mongo
      args:
        - MONGO_VERSION=${MONGO_VERSION}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${API_DATABASE_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${API_DATABASE_PASSWORD}
      MONGO_INITDB_DATABASE: ${API_DATABASE_NAME}
    volumes:
      - ${DATA_PATH_HOST}/mongo:/data/db
    networks:
      - backend
    labels:
      - traefik.enable=false

  ### Mongo Express ##############################################
  mongo-express:
    depends_on:
      - mongo
    image: mongo-express
    networks:
      - frontend
      - backend
    environment:
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${API_DATABASE_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${API_DATABASE_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
      ME_CONFIG_MONGODB_ENABLE_ADMIN: ${ME_CONFIG_MONGODB_ENABLE_ADMIN}
      ME_CONFIG_MONGODB_AUTH_DATABASE: ${API_DATABASE_AUTHENTICATION_DATABASE}
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${API_DATABASE_USERNAME}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${API_DATABASE_PASSWORD}
    labels:
      - "traefik.backend=${TB_MONGO_EXPRESS}"
      - "traefik.frontend.rule=Host:${MONGO_EXPRESS_HOST_URL}"
      - "traefik.port=${MONGO_EXPRESS_CONTAINER_PORT}"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_frontend"

  ### Jenkins ###################################################
  jenkins:
    build: ./jenkins
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "${JENKINS_HOST_SLAVE_AGENT_PORT}:50000"
      # - "${JENKINS_HOST_HTTP_PORT}:8080"
    privileged: true
    volumes:
      - ${JENKINS_HOME}:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend
      - backend
    labels:
      - "traefik.backend=${TB_JENKINS}"
      - "traefik.frontend.rule=Host:${JENKINS_HOST_URL}"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_frontend"
      - "traefik.port=${JENKINS_CONTAINER_PORT}"

  ### Webhook ###################################################
  webhook:
    build: ./webhook
    volumes:
      - ${WEBHOOK_HOOKS_DIR}:/etc/webhook
      - ${WEBHOOK_SCRIPTS_DIR}:/opt/scripts
      - ${APP_CODE_PATH_HOST}:/opt/deploy
    networks:
      - frontend
    labels:
      - "traefik.backend=${TB_WEBHOOK}"
      - "traefik.frontend.rule=Host:${WEBHOOK_HOST_URL}"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_frontend"
      - "traefik.port=${WEBHOOK_CONTAINER_PORT}"

  ### Adminer ################################################
  adminer:
    depends_on:
      - ${ADMINER_HOST}
    image: adminer:4.7.3-standalone
    restart: unless-stopped
    environment:
      - ADMINER_DESIGN=${ADMINER_DESIGN}
    networks:
      - frontend
      - backend
    labels:
      - "traefik.backend=${TB_ADMINER}"
      - "traefik.frontend.rule=Host:${ADMINER_HOST_URL}"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_frontend"
      - "traefik.port=${ADMINER_CONTAINER_PORT}"


  ### Redis ################################################
  redis:
    build: ./redis
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend
    labels:
      - traefik.enable=false

  ### Redis Cluster ##########################################
  redis-cluster:
    build: ./redis-cluster
    ports:
      - "${REDIS_CLUSTER_PORT_RANGE}:7000-7005"
    networks:
      - backend
    labels:
      - traefik.enable=false

  ### REDISWEBUI ################################################
  redis-webui:
    build:
      context: ./redis-webui
    environment:
      - ADMIN_USER=${REDIS_WEBUI_USERNAME}
      - ADMIN_PASS=${REDIS_WEBUI_PASSWORD}
      - REDIS_1_HOST=${REDIS_WEBUI_CONNECT_HOST}
      - REDIS_1_PORT=${REDIS_WEBUI_CONNECT_PORT}
    networks:
      - frontend
      - backend
    depends_on:
      - redis
    labels:
      - "traefik.backend=${TB_REDIS_WEBUI}"
      - "traefik.frontend.rule=Host:${REDIS_WEBUI_HOST_URL}"
      - "traefik.docker.network=${COMPOSE_PROJECT_NAME}_frontend"
      - "traefik.port=${REDIS_WEBUI_CONTAINER_PORT}"

  ### TRAEFIK #########################################
  traefik:
    build:
      context: ./traefik
    restart: always
    environment:
      - DO_AUTH_TOKEN=${TRAEFIK_DO_AUTH_TOKEN}
      - NAMECHEAP_API_USER=${TRAEFIK_NAMECHEAP_API_USER}
      - NAMECHEAP_API_KEY=${TRAEFIK_NAMECHEAP_API_KEY}
    command: --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/acme:/etc/traefik/acme
    ports:
      - "${TRAEFIK_HOST_HTTP_PORT}:80"
      - "${TRAEFIK_HOST_HTTPS_PORT}:443"
    networks:
      - frontend
    labels:
      - "traefik.backend=${TB_TRAEFIK}"
      - "traefik.frontend.rule=Host:${TRAEFIK_HOST_URL}"
      - "traefik.port=8080"