# @format

version: '3.9'

networks:
  backend:
    driver: '${NETWORKS_DRIVER}'
  dockernet:
    external: true
  backdocker:
    external: true

volumes:
  drone:
    driver: '${VOLUMES_DRIVER}'
  strapi:
    driver: '${VOLUMES_DRIVER}'
  webhook:
    driver: '${VOLUMES_DRIVER}'
  elasticsearch:
    driver: '${VOLUMES_DRIVER}'
  fusionauth:
    driver: '${VOLUMES_DRIVER}'

services:
  # https://github.com/soyuka/explorer.git
  # EXPLORER ################################################
  explorer:
    image: stctheproducer/explorer
    expose:
      - 4859
    networks:
      - dockernet
    volumes:
      - './explorer/examples:/opt/explorer'
    labels:
      - 'traefik.enable=true'

  # WHOAMI ################################################
  whoami:
    image: emilevauge/whoami
    networks:
      - dockernet
    labels:
      - 'traefik.enable=true'

  ## STRAPI ################################################
  strapi:
    depends_on:
      - '${API_DATABASE_CLIENT}'
    image: strapi/strapi
    restart: unless-stopped
    networks:
      - dockernet
      - backend
    environment:
      - 'DATABASE_CLIENT=${API_DATABASE_CLIENT}'
      - 'DATABASE_NAME=${API_DATABASE_NAME}'
      - 'DATABASE_HOST=${API_DATABASE_HOST}'
      - 'DATABASE_PORT=${API_DATABASE_PORT}'
      - 'DATABASE_USERNAME=${API_DATABASE_USER}'
      - 'DATABASE_PASSWORD=${API_DATABASE_PASSWORD}'
    volumes:
      - '${DATA_PATH_HOST}/strapi:/srv/app'
    labels:
      - 'traefik.enable=true'

  ### Webhook ################################################
  webhook:
    build:
      context: ./webhook
      args:
        - 'WEBHOOK_VERSION=${WEBHOOK_VERSION}'
    restart: unless-stopped
    environment:
      DRONE_WEBHOOK_SECRET: ${DRONE_WEBHOOK_SECRET}
      DRONE_SERVER_HOST: ${DRONE_SERVER_HOST}
      SSH_AUTH_SOCK: /ssh-agent
    volumes:
      - '${WEBHOOK_HOOKS_DIR}:/etc/webhook'
      - '${WEBHOOK_SCRIPTS_DIR}:/opt/scripts'
      - '${APP_PROJECTS}:/opt/deploy'
      - '${SSH_AUTH_SOCK}:/ssh-agent'
      - '/var/run/docker.sock:/var/run/docker.sock'
      - './logs/apps/webhook.log:/root/logs/webhook.log'
    networks:
      - dockernet
    labels:
      - 'traefik.enable=true'

  ### FUSIONAUTH ########################################
  fusionauth:
    image: 'fusionauth/fusionauth-app:${FUSIONAUTH_VERSION}'
    restart: unless-stopped
    volumes:
      - fusionauth:/usr/local/fusionauth/config
      - ./fusionauth/kickstart:/usr/local/fusionauth/kickstart
    env_file: ./fusionauth/.env
    environment:
      DATABASE_URL: ${FUSIONAUTH_DATABASE_URL}://${API_DATABASE_CLIENT}:${API_DATABASE_PORT}/${FUSIONAUTH_DATABASE_NAME}
      DATABASE_USERNAME: ${FUSIONAUTH_DATABASE_USER}
      DATABASE_PASSWORD: ${FUSIONAUTH_DATABASE_PASSWORD}
      DATABASE_ROOT_USERNAME: ${API_DATABASE_USER}
      DATABASE_ROOT_PASSWORD: ${API_DATABASE_PASSWORD}
      FUSIONAUTH_APP_MEMORY: ${FUSIONAUTH_APP_MEMORY}
      # SEARCH_SERVERS: ${SEARCH_SERVERS}
      SEARCH_TYPE: ${SEARCH_TYPE}
      FUSIONAUTH_APP_RUNTIME_MODE: ${FUSIONAUTH_APP_RUNTIME_MODE}
      FUSIONAUTH_APP_SILENT_MODE: ${FUSIONAUTH_APP_SILENT_MODE}
      FUSIONAUTH_APP_URL: ${FUSIONAUTH_APP_URL}
      FUSIONAUTH_APP_KICKSTART_FILE: ${FUSIONAUTH_APP_KICKSTART_FILE}
    depends_on:
      - ${API_DATABASE_CLIENT}
      # - elasticsearch
      - traefik
    networks:
      dockernet:
        ipv4_address: 192.168.1.10
      backend: {}
    # ports:
    # - 9011:${FUSIONAUTH_CONTAINER_PORT}
    labels:
      - 'traefik.enable=true'

  ### LOGOWL ########################################
  logowl:
    image: jz222/logowl:${LOGOWL_VERSION}
    environment:
      SECRET: ${LOGOWL_SECRET}
      PORT: ${LOGOWL_CONTAINER_PORT}
      MONGO_URI: 'mongodb://${LOGOWL_DB_USER}:${LOGOWL_DB_PASSWORD}@mongo:27017/${LOGOWL_MONGO_DB_NAME}?retryWrites=false'
      MONGO_DB_NAME: ${LOGOWL_MONGO_DB_NAME}
      CLIENT_URL: ${LOGOWL_CLIENT_URL}
      MONTHLY_REQUEST_LIMIT: ${LOGOWL_MONTHLY_REQUEST_LIMIT}
      IS_SELFHOSTED: ${LOGOWL_IS_SELFHOSTED}
      MAILGUN_PRIVATE_KEY: ${MAILGUN_PRIVATE_KEY}
      MAILGUN_DOMAIN: ${MAILGUN_DOMAIN}
      MAILGUN_API_BASE: ${MAILGUN_API_BASE}
    networks:
      - backend
      - dockernet
    labels:
      - 'traefik.enable=true'

  ### FILEBEAT ########################################
  filebeat-apps:
    build:
      context: ./filebeat
      args:
        - 'FILEBEAT_VERSION=${FILEBEAT_VERSION}'
    env_file: ./filebeat/.env
    volumes:
      - './filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro'
      - './logs:/usr/share/filebeat/logs'
  filebeat-containers:
    image: logzio/docker-collector-logs
    # command: 'python3 docker-colletor-logs/filebeat-yml-script.py --matchContainerName='fusionauth''
    env_file: ./filebeat/.env
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
      - '/var/lib/docker/containers:/var/lib/docker/containers'

  ### DRONE CI ########################################
  drone:
    image: drone/drone:${DRONE_VERSION}
    restart: always
    environment:
      DRONE_DATABASE_DRIVER: ${DRONE_DATABASE_DRIVER}
      DRONE_DATABASE_DATASOURCE: ${DRONE_DATABASE_DRIVER}://${DRONE_DATABASE_USER}:${DRONE_DATABASE_PASSWORD}@${API_DATABASE_CLIENT}:${API_DATABASE_PORT}/${DRONE_DATABASE_NAME}?sslmode=disable
      DRONE_DATABASE_SECRET: ${DRONE_DATABASE_SECRET}
      DRONE_GITHUB_CLIENT_ID: ${DRONE_GITHUB_CLIENT_ID}
      DRONE_GITHUB_CLIENT_SECRET: ${DRONE_GITHUB_CLIENT_SECRET}
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_SERVER_HOST: ${DRONE_SERVER_HOST}
      DRONE_SERVER_PROTO: ${DRONE_SERVER_PROTO}
      # DRONE_WEBHOOK_ENDPOINT: ${DRONE_WEBHOOK_ENDPOINT}
      # DRONE_WEBHOOK_EVENTS: ${DRONE_WEBHOOK_EVENTS}
      # DRONE_WEBHOOK_SECRET: ${DRONE_WEBHOOK_SECRET}
    volumes:
      - 'drone:/data'
    networks:
      dockernet:
        ipv4_address: 192.168.1.5
      backend: {}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.drone.rule=Host(`drone.${DOMAIN_NAME})'
      - 'traefik.http.routers.drone.entrypoints=websecure'
      - 'traefik.http.routers.drone.tls=true'
      - 'traefik.http.routers.drone.tls.certresolver=letsEncryptDnsCustom'
      - 'traefik.http.services.drone.loadbalancer.server.port=80'

  ### DRONE RUNNER ########################################
  drone-runner:
    image: drone/drone-runner-digitalocean
    restart: always
    environment:
      DRONE_RPC_SECRET: ${DRONE_RPC_SECRET}
      DRONE_RPC_HOST: ${DRONE_RPC_HOST}
      DRONE_SERVER_PROTO: ${DRONE_SERVER_PROTO}
      DRONE_PUBLIC_KEY_FILE: ${DRONE_PUBLIC_KEY_FILE}
      DRONE_PRIVATE_KEY_FILE: ${DRONE_PRIVATE_KEY_FILE}
    volumes:
      - '/home/${USER}/.ssh/drone_runner:${DRONE_PRIVATE_KEY_FILE}'
      - '/home/${USER}/.ssh/drone_runner.pub:${DRONE_PUBLIC_KEY_FILE}'
    networks:
      - dockernet

  ### OATHKEEPER ########################################
  oathkeeper:
    image: oryd/oathkeeper:${OATHKEEPER_VERSION}
    command: serve --config=/etc/oathkeeper/config.yaml
    restart: unless-stopped
    expose:
      - 4455
      - 4456
    networks:
      - dockernet
    volumes:
      - './ory/oathkeeper/files:/etc/oathkeeper'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.oathkeeper-proxy.rule=Host(`${OATHKEEPER_PROXY_SUBDOMAIN}.${DOMAIN_NAME}`)'
      - 'traefik.http.routers.oathkeeper-proxy.entrypoints=websecure'
      - 'traefik.http.routers.oathkeeper-proxy.tls=true'
      - 'traefik.http.routers.oathkeeper-proxy.service=oathkeeper-proxy'
      - 'traefik.http.services.oathkeeper-proxy.loadbalancer.server.port=${OATHKEEPER_PROXY_PORT}'
      # -
      - 'traefik.http.routers.oathkeeper-api.rule=Host(`${OATHKEEPER_API_SUBDOMAIN}.${DOMAIN_NAME}`)'
      - 'traefik.http.routers.oathkeeper-api.entrypoints=websecure'
      - 'traefik.http.routers.oathkeeper-api.tls=true'
      - 'traefik.http.routers.oathkeeper-api.service=oathkeeper-api'
      - 'traefik.http.services.oathkeeper-api.loadbalancer.server.port=${OATHKEEPER_API_PORT}'

  ### KETO ########################################
  keto-migrate:
    image: oryd/keto:${KETO_VERSION}
    command: migrate sql -e
    restart: on-failure
    environment:
      LOG_LEVEL: debug
      DSN: ${KETO_DSN}
    networks:
      - backdocker
    labels:
      - 'traefik.enable=false'

  keto:
    image: oryd/keto:${KETO_VERSION}
    depends_on:
      - keto-migrate
    command: serve --config=/etc/keto/config.yaml
    restart: unless-stopped
    environment:
      DSN: ${KETO_DSN}
    expose:
      - 4466
    networks:
      - dockernet
      - backdocker
    volumes:
      - './ory/keto/files:/etc/keto'
    labels:
      - 'traefik.enable=true'

  ### KRATOS ########################################
  kratos-migrate:
    image: oryd/kratos:${KRATOS_VERSION}
    command: migrate sql -e --config=/etc/config/kratos/.kratos.yml -y
    restart: on-failure
    environment:
      LOG_LEVEL: debug
      DSN: ${KRATOS_DSN}
    networks:
      - backdocker
    volumes:
      - './ory/kratos/files:/etc/config/kratos'
    labels:
      - 'traefik.enable=false'

  kratos:
    image: oryd/kratos:${KRATOS_VERSION}
    depends_on:
      - kratos-migrate
    command: serve --config=/etc/config/kratos/.kratos.yml --dev
    restart: unless-stopped
    environment:
      LOG_LEVEL: trace
      DSN: ${KRATOS_DSN}
    expose:
      - 4433
      - 4434
    networks:
      - dockernet
      - backdocker
    volumes:
      - './ory/kratos/files:/etc/config/kratos'
      - './ory/kratos/email-templates:/etc/config/courier-templates'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.kratos-public.rule=Host(`${KRATOS_PUBLIC_SUBDOMAIN}.${DOMAIN_NAME}`)'
      - 'traefik.http.routers.kratos-public.entrypoints=websecure'
      - 'traefik.http.routers.kratos-public.tls=true'
      - 'traefik.http.routers.kratos-public.service=kratos-public'
      - 'traefik.http.services.kratos-public.loadbalancer.server.port=${KRATOS_PUBLIC_PORT}'
      # -
      - 'traefik.http.routers.kratos-admin.rule=Host(`${KRATOS_ADMIN_SUBDOMAIN}.${DOMAIN_NAME}`)'
      - 'traefik.http.routers.kratos-admin.entrypoints=websecure'
      - 'traefik.http.routers.kratos-admin.tls=true'
      - 'traefik.http.routers.kratos-admin.service=kratos-admin'
      - 'traefik.http.services.kratos-admin.loadbalancer.server.port=${KRATOS_ADMIN_PORT}'

  ### MAILSLURPER ########################################
  kratos-mail:
    image: oryd/mailslurper:latest-smtps
    # command: mailslurper -loglevel debug -logformat simple
    expose:
      - 4436
      - 4437
      - 1025
    ports:
      - '4436:4436'
      - '4437:4437'
      - '1025:1025'
    networks:
      - dockernet
    labels:
      - 'traefik.enable=false'
