version: '3.9'

networks:
  dockernet:
    external: true
  backdocker:
    external: true

services:
  # Authelia (Lite) - Self-Hosted Single Sign-On and Two-Factor Authentication
  authelia:
    container_name: authelia
    # image: authelia/authelia:latest
    image: authelia/authelia:4
    restart: always
    expose:
      - 9091
    networks:
      - dockernet
      - backdocker
    depends_on:
      - mariadb
      - redis
    volumes:
      - './authelia/config:/config'
    env_file:
      - ./authelia/.env
    secrets:
      - authelia_jwt_secret
      - authelia_session_secret
      - authelia_storage_encryption_key
      - authelia_storage_mysql_password
      - authelia_notifier_smtp_password
      - authelia_duo_api_secret_key
    labels:
      - 'traefik.enable=true'
      ## HTTP Routers
      - 'traefik.http.routers.authelia.entrypoints=websecure'
      - 'traefik.http.routers.authelia.rule=Host(`authelia.${DOMAIN_NAME}`)'
      - 'traefik.http.routers.authelia.tls=true'
      - 'traefik.http.routers.authelia.tls.certresolver=cloudflareDns'
      # Middlewares
      - 'traefik.http.routers.authelia.middlewares=chain-no-auth@file'

secrets:
  authelia_jwt_secret:
    file: $SECRETSDIR/authelia_jwt_secret
  authelia_session_secret:
    file: $SECRETSDIR/authelia_session_secret
  authelia_storage_encryption_key:
    file: $SECRETSDIR/authelia_storage_encryption_key
  authelia_storage_mysql_password:
    file: $SECRETSDIR/authelia_storage_mysql_password
  authelia_notifier_smtp_password:
    file: $SECRETSDIR/authelia_notifier_smtp_password
  authelia_duo_api_secret_key:
    file: $SECRETSDIR/authelia_duo_api_secret_key
  # authelia_session_redis_password:
  #   file: $SECRETSDIR/authelia_session_redis_password
