# @format

version: '3.9'

# SECRETS ################################################
secrets:
  cloudflare_email:
    file: $SECRETSDIR/cloudflare_email
  cloudflare_api_key:
    file: $SECRETSDIR/cloudflare_api_key

# Examples below
services:
  app:
    secrets:
      - cloudflare_email
      - cloudflare_api_key
    # Notice that the environmental variables now have _FILE appended at the end. Don't miss this or it won't work.
    environment:
      - CF_API_EMAIL_FILE=/run/secrets/cloudflare_email
      - CF_API_KEY_FILE=/run/secrets/cloudflare_api_key