ARG TRAEFIK_VERSION=2

FROM traefik:${TRAEFIK_VERSION}

LABEL maintainer="Luis Coutinho <luis@luiscoutinho.pt>"

# RUN chmod 600 /certs/cert.key /certs/cert.includesprivatekey.pem
# RUN chmod 644 /certs/cert.crt
