################################################################
# Global configuration
################################################################

global:
  checkNewVersion: true
  sendAnonymousUsage: false

serversTransport:
  insecureSkipVerify: true
  rootCAs:
    - foo.crt
    - bar.crt

################################################################
# Entrypoints configuration
################################################################

# Entrypoints definition
#
# Optional
# Default:

entryPoints:
  web:
    # Listen on port 80 for incoming requests
    address: ":80"
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32"
        - "192.168.8.1/24"

  websecure:
    address: ":443"
    forwardedHeaders:
      trustedIPs:
        - "127.0.0.1/32"
        - "192.168.8.1/24"

  mysql:
    address: ":3306"

  metrics:
    address: ":8082"

#   ping:
#     address: ":8082"

# ping:
#   entryPoint: "ping"
################################################################
# API and dashboard configuration
################################################################

# Enable API and dashboard
api:
  # Enabled Dashboard
  #
  # Optional
  # Default: true
  #
  dashboard: true

  # Enable the API in insecure mode
  #
  # Optional
  # Default: true
  #
  insecure: true
  debug: true

################################################################
# Docker configuration backend
################################################################

# Enable Docker configuration backend
providers:
  providersThrottleDuration: 10s
  docker:
    # Docker server endpoint. Can be a tcp or a unix socket endpoint.
    #
    # Required
    # Default: "unix:///var/run/docker.sock"
    #
    endpoint: "tcp://socket-proxy:2375"
    # Default host rule.
    #
    # Optional
    # Default: "Host(`{{ normalize .Name }}`)"
    #
    # defaultRule: "Host(`{{ normalize .Name }}.local.test`)"
    defaultRule: 'Host(`{{ index .Labels "com.get.host.url"}}`)'

    # Secure connection certificates
    # tls:
    #   ca: path/to/ca.crt
    #   caOptional: true
    #   cert: path/to/foo.cert
    #   key: path/to/foo.key
    #   insecureSkipVerify: true
    # Expose containers by default in traefik
    #
    # Optional
    # Default: true
    #
    network: local_frontend
    exposedByDefault: false
    useBindPortIP: true

  file:
    # Enable the file provider to define routers / middlewares / services in file
    directory: /etc/traefik/dynamic
    watch: true
    debugLogGeneratedTemplate: true

################################################################
# Traefik logs configuration
################################################################

# Traefik logs
# Enabled by default and log to stdout
#
# Optional
#
log:
  level: DEBUG
  filePath: logs/traefik.log
  # format: json

################################################################
# Access logs configuration
################################################################

# Enable access logs
# By default it will write to stdout and produce logs in the textual
# Common Log Format (CLF), extended with additional fields.
#
# Optional
#
accessLog:
  filePath: /logs/access_log.log
  # format: json
  bufferingSize: 1000
  filters:
    statusCodes:
      - "200"
      - "300-302"
    retryAttempts: true
    minDuration: "10ms"
  fields:
    defaultMode: keep
    names:
      ClientUsername: drop
    headers:
      defaultMode: keep
      names:
        User-Agent: redact
        Authorization: drop
        Content-Type: keep

################################################################
# Metrics Configuration
################################################################

metrics:
  datadog:
    address: 127.0.0.1:8125
    pushInterval: 42s
    addEntryPointsLabels: true
    addServicesLabels: true

  influxDB:
    address: localhost:8089
    # @Required
    protocol: udp
    database: "db"
    retentionPolicy: "two_hours"
    # Only with http
    username: "john"
    password: "secret"
    # ------------------
    addEntryPointsLabels: true
    addServicesLabels: true
    pushInterval: 42s

  prometheus:
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    addEntryPointsLabels: true
    addServicesLabels: true
    entryPoint: metrics
    # If manualRouting is true, it disables the default internal router in order
    # to allow one to create a custom router for the prometheus@internal service.
    manualRouting: true

  statsD:
    address: localhost:8125
    addEntryPointsLabels: true
    addServicesLabels: true
    pushInterval: 42s
    prefix: traefik

################################################################
# Tracing Configuration
################################################################

tracing:
  serviceName: traefik
  spanNameLimit: 150
  jaeger:
    samplingServerURL: http://localhost:5778/sampling
    # const, probabilistic, rateLimiting
    samplingType: const

    # for const sampler, 0 or 1 for always false/true respectively
    # for probabilistic sampler, a probability between 0 and 1
    # for rateLimiting sampler, the number of spans per second
    samplingParam: 1.0
    localAgentHostPort: 27.0.0.1:6831
    # Default: false
    gen128Bit: true
    propagation: jaeger
    # @Required
    traceContextHeaderName: uber-trace-id
    collector:
      endpoint: http://127.0.0.1:14268/api/traces?format=jaeger.thrift
      user: my-user
      password: my-password

  zipkin:
    httpEndpoint: http://localhost:9411/api/v2/spans
    # Default: false
    sameSpan: true
    id128Bit: true
    sampleRate: 0.2 # 0.0 -- 1.0

  datadog:
    localAgentHostPort: 127.0.0.1:8126
    debug: true
    globalTag: sample
    prioritySampling: true

  instana:
    localAgentHost: 127.0.0.1
    localAgentPort: 42699
    # error, warn, debug, info
    logLevel: info

  haystack:
    localAgentHost: 127.0.0.1
    localAgentPort: 35000
    globalTag: sample:test
    traceIDHeaderName: Trace-ID
    parentIDHeaderName: Parent-Message-ID
    spanIDHeaderName: Message-ID
    baggagePrefixHeaderName: sample

hostResolver:
  cnameFlattening: true
  resolvConfig: foobar
  resolvDepth: 42
