global:
  checkNewVersion: true

entryPoints:
  web:
    address: ":80"
  metrics:
    address: ":8082"

api:
  dashboard: true
  insecure: true
  debug: true

providers:
  providersThrottleDuration: 10
  docker:
    endpoint: "tcp://socket-proxy:2375"
    network: dockernet
    exposedByDefault: false
    watch: true

  file:
    # Enable the file provider to define routers / middlewares / services in file
    directory: /etc/traefik/dynamic
    watch: true

accessLog:
  # filePath: /logs/access_log.log
  bufferingSize: 1000

log:
  level: DEBUG
  # filePath: /logs/traefik.log
