global:
  checkNewVersion: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  mysql:
    address: ":3306"
  metrics:
    address: ":8082"

api:
  dashboard: true
  insecure: false
  debug: false

providers:
  providersThrottleDuration: 10s
  docker:
    endpoint: "tcp://socket-proxy:2375"
    network: local_frontend
    exposedByDefault: false
    watch: true
  file:
    # Enable the file provider to define routers / middlewares / services in file
    directory: /etc/traefik/dynamic
    watch: true

log:
  level: ERROR
  filePath: /logs/traefik.json
  format: json

certificatesResolvers:
  # Note that Let's Encrypt API has rate limiting.
  #
  # Use Let's Encrypt staging server with the caServer
  # configuration option when experimenting to avoid hitting
  # this limit too fast.
  letsEncryptDns:
    acme:
      email: email@address.com
      #  Staging Server
      caServer: https://acme-staging-v02.api.letsencryptorg/directory"
      # Production server
      # caServer: https://acme-v02.api.letsencrypt.org/directory
      storage: /etc/traefik/acme/acme.json
      dnsChallenge:
        provider: namecheap
        delayBeforeCheck: 42

  letsEncryptHttp:
    acme:
      email: email@address.com
      #  Staging Server
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      # Production server
      # caServer: https://acme-v02.api.letsencrypt.org/directory
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

  letsEncryptTls:
    acme:
      email: email@address.com
      #  Staging Server
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      # Production server
      # caServer: https://acme-v02.api.letsencrypt.org/directory
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: websecure
      tlsChallenge: {}

  letsEncryptDnsCustom:
    acme:
      email: email@address.com
      #  Staging Server
      # caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      # Production server
      # caServer: https://acme-v02.api.letsencrypt.org/directory
      storage: /etc/traefik/acme/acme.json
      dnsChallenge:
        provider: namecheap
        delayBeforeCheck: 42
        resolvers:
          - "1.1.1.1:53"
          - "8.8.8.8:53"
