FROM node:lts-alpine

# make the '/usr/app' folder the current working directory
WORKDIR /usr/app

# Change ownership of work directory for good measure
RUN chown -R node:node /usr/app

# install several dependencies
# RUN apk add --no-cache build-base gcc autoconf automake libtool zlib-dev libpng-dev nasm

# switch to non-root user
USER node

# copy 'package.json'
COPY --chown=node:node ./package.json ./

# install project dependencies
RUN yarn

# copy project files and folders to the current working directory
COPY --chown=node:node . .

EXPOSE 3000
CMD ["yarn", "dev"]
