http:
  routers:
    redirecttohttps:
      entryPoints:
        - web
      middlewares:
        - redirectallhttp
      rule: "HostRegexp(`{host:.+}`)"
      service: noop

  services:
    noop:
      loadBalancer:
        servers:
          - url: "http://192.168.53.1"

  middlewares:
    redirectallhttp:
      redirectScheme:
        scheme: https
