http:
  routers:
    https-redirect:
      entryPoints:
        - "web"
      middlewares:
        - https-redirect
      rule: "HostRegexp(`{any:.*}`)"
      service: noop

  services:
    noop:
      loadBalancer:
        servers:
          - url: "http://192.168.53.1"

  middlewares:
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: "true"
        port: 443
