# ! DO NOT LEAVE WHITESPACE AT THE BRACKET ENDS
http:
  routers:
    serviceName:
      rule: Host(`serviceName.{{env "DOMAIN_NAME"}}`)
      entryPoints:
        - web
      middlewares:
        - redirecthttp
      service: serviceName-{{env "COMPOSE_PROJECT_NAME"}}@docker
    serviceName-secure:
      rule: Host(`serviceName.{{env "DOMAIN_NAME"}}`)
      entryPoints:
        - websecure
      tls: {}
      service: serviceName-{{env "COMPOSE_PROJECT_NAME"}}@docker
