# ! DO NOT LEAVE WHITESPACE AT THE BRACKET ENDS
http:
  routers:
    serviceName:
      rule: Host(`serviceName.{{env "DOMAIN_NAME"}}`)
      entryPoints:
        - web
      middlewares:
        - redirecthttp
      service: serviceName
    serviceName-secure:
      rule: Host(`serviceName.{{env "DOMAIN_NAME"}}`)
      entryPoints:
        - websecure
      tls: {}
      # tls:
      # certResolver: cloudflareDns
      service: serviceName

  services:
    serviceName:
      loadBalancer:
        servers:
          - url: http://192.168.1.1:{{PORT_NUMBER_OF_SERVICE}}
