# This is meant to be run on the server that is connected to in the reverse SSH tunnel
http:
  routers:
    service:
      entryPoints:
        - websecure
      rule: Host(`service-dev.{{env "DOMAIN_NAME"}}`)
      service: dev
      tls:
        certResolver: letsEncryptDns
    service-api:
      entryPoints:
        - websecure
      rule: Host(`service-api-dev.{{env "DOMAIN_NAME"}}`)
      service: dev
      tls:
        certResolver: letsEncryptDns

  services:
    dev:
      loadBalancer:
        servers:
          - url: http://192.168.1.1:{{PORT_NUMBER_OF_LOCAL_MACHINE}}
