# ! DO NOT LEAVE WHITESPACE AT THE BRACKET ENDS
http:
  routers:
    portainer:
      rule: Host(`portainer.{{env "DOMAIN_NAME"}}`)
      entryPoints:
        - websecure
      tls: {}
      service: portainer-{{env "COMPOSE_PROJECT_NAME"}}@docker
