# ! DO NOT LEAVE WHITESPACE AT THE BRACKET ENDS
http:
  routers:
    serviceName:
      rule: Host(`serviceName.{{env "DOMAIN_NAME"}}`)
      entryPoints:
        - web
      middlewares:
        - redirecthttp
      service: serviceName-{{env "COMPOSE_PROJECT_NAME"}}@docker
    serviceName-secure:
      rule: Host(`serviceName.{{env "DOMAIN_NAME"}}`)
      entryPoints:
        - websecure
      tls: {}
      service: serviceName-{{env "COMPOSE_PROJECT_NAME"}}@docker
    serviceName-fwd:
      rule: Host(`{{env "TUNNEL_URL"}}`) && Path(`/serviceName`)
      entryPoints:
        - websecure
      middlewares:
        - pathstrip
      service: serviceName-{{env "COMPOSE_PROJECT_NAME"}}@docker
    serviceName-reverse:
      rule: Host(`serviceName.{{env "TUNNEL_URL"}}`)
      entryPoints:
        - websecure
      middlewares:
        - pathstrip
      service: serviceName-{{env "COMPOSE_PROJECT_NAME"}}@docker
  # services:
  #   serviceName:
  #     loadBalancer:
  #       servers:
  #         - url: http://serviceName:{{ env "SERVICE_CONTAINER_PORT" }}
